apiVersion: v1
kind: Pod
metadata:
  name: hello-pong-pod
  labels:
    app: hello-pong
spec:
  containers:
  - name: hello-pong
    image: hackerman/hello-pong:latest
    ports:
    - containerPort: 8080